FROM alpine:3.22

RUN  apk update
RUN sudo apk add \
        sudo         \
        tar          \
        wget         \
        git          \
        pkgconfig    \
        ruby         \
        cmake        \
        make         \
        gcc          \
        g++          \
        gettext      \
        openjdk8     \
        jq